// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOr5xfP0UrYfMJzte84qQ-cEEajNp83ig',
    appId: '1:372588568893:web:d84f2c8d301600263e6554',
    messagingSenderId: '372588568893',
    projectId: 'accomy-cit',
    authDomain: 'accomy-cit.firebaseapp.com',
    storageBucket: 'accomy-cit.firebasestorage.app',
    measurementId: 'G-J74CB2XT9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGypojIz01t98s-SoTtA1zPB9LaRxQvdI',
    appId: '1:372588568893:android:289e6f5a878336fb3e6554',
    messagingSenderId: '372588568893',
    projectId: 'accomy-cit',
    storageBucket: 'accomy-cit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBykYDbN7YW8pJAAixf6TldZltnkqmxGSk',
    appId: '1:372588568893:ios:ad94e7d8f5931c2c3e6554',
    messagingSenderId: '372588568893',
    projectId: 'accomy-cit',
    storageBucket: 'accomy-cit.firebasestorage.app',
    iosClientId: '372588568893-50pn8023v5456t4dhfgv9j2m07eb30tn.apps.googleusercontent.com',
    iosBundleId: 'com.example.accomy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBykYDbN7YW8pJAAixf6TldZltnkqmxGSk',
    appId: '1:372588568893:ios:ad94e7d8f5931c2c3e6554',
    messagingSenderId: '372588568893',
    projectId: 'accomy-cit',
    storageBucket: 'accomy-cit.firebasestorage.app',
    iosClientId: '372588568893-50pn8023v5456t4dhfgv9j2m07eb30tn.apps.googleusercontent.com',
    iosBundleId: 'com.example.accomy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOr5xfP0UrYfMJzte84qQ-cEEajNp83ig',
    appId: '1:372588568893:web:abebae7ac138590a3e6554',
    messagingSenderId: '372588568893',
    projectId: 'accomy-cit',
    authDomain: 'accomy-cit.firebaseapp.com',
    storageBucket: 'accomy-cit.firebasestorage.app',
    measurementId: 'G-5K8PHF4LBE',
  );
}
